name: Danger
on:
  pull_request:
    types: [opened, edited, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v4

      - name: install DangerJS
        run: npm install -g danger

      - name: Build DangerRunner
        working-directory: DangerRunner
        run: swift build -c release

      - name: Run Danger
        working-directory: DangerRunner
        run: swift run danger-swift ci --cwd ../
